### ISSUE TITLE
setDebugMode should be a mulch-wide setting

### ISSUE THREAD

**Issue by helenginn** [mulch-environment/mulch#13]
At the moment `setDebugMode` is listed under `Collection` but it isn't necessarily related to `Collection`, so it should be under the `mulch` namespace and not related to/referred to in files for any particular class. (For example maybe I should have to import `Debug.h` if I want to alter the setting)

**Comment by virginia4** [comment]
The way I use it is that I include the line: mulch::DebugLog::setDebugMode(false); at the beginning of my test. It seems to be working for all the classes when I do that.

**Comment by helenginn** [comment]
Then this means that the line `virtual void setDebugMode(bool mode) = 0;` in `Collection.h` should be removed as it isn't necessary to call setDebugMode from the `mulch::Collection::` namespace!
