### ISSUE TITLE
Return a newly created ModelDataPair so I can make further changes before saving to the database

### ISSUE THREAD

**Issue by helenginn** [mulch-environment/mulch#16]
When the user adds a ModelDataPair, e.g. `c->addModel(Atomic, "3dpw.pdb");`, `c->addModel(Xray, "3dpw.mtz");` or `c->addModelDataPair(Atomic, "3dpw.pdb", Xray, "3dpw.mtz")` then the code creates a new `ModelDataPair` and stores it in the `Collection`. It would be great if these functions could be modified so instead of returning `void`, it returns the `ModelDataPair *` pointer so the user can make further changes to the `ModelDataPair` object in their own code.

**Comment by virginia4** [comment]
Commits made on 22.09.2023 should address and solve this issue
